name = "my-tasks-worker"
type = "javascript"
main = "worker.ts"
compatibility_date = "2025-02-27"

[triggers]
crons = ["*/1 * * * *"]

[durable_objects]
bindings = [
  { name = "SCHEDULER_LOCK", class_name = "SchedulerLock" }
]
