name = "my-tasks-worker"
# type は自動で処理されるため、明示しなくても問題ありません
main = "worker.ts"
compatibility_date = "2025-02-27"

[triggers]
crons = ["*/1 * * * *"]

[durable_objects]
bindings = [
  { name = "SCHEDULER_LOCK", class_name = "SchedulerLock" }
]

[[migrations]]
tag = "v1"
new_classes = [ "SchedulerLock" ]
