# .github/workflows/notify-tasks.yml
name: Notify Tasks

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Supabase Edge Function
        run: |
          curl -L -X POST "https://gmzfuhrzoexumlterark.supabase.co/functions/v1/notify-tasks" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtemZ1aHJ6b2V4dW1sdGVyYXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0OTY5NzYsImV4cCI6MjA1NjA3Mjk3Nn0.OWkn9cnQW2KsVC2WqdQcGRTpSIJqpaVJRJATLUPTpkY" \
            -H "Content-Type: application/json" \
            --data "{\"name\":\"Functions\"}"
